@Web_HostAddress = http://localhost:5268

POST {{Web_HostAddress}}/api/createReservationJob
Accept: application/json
Content-Type: application/json

{
  "trainingId": "exampleTrainingId",
  "memberId": "exampleMemberId",
  "userToken": "exampleUserToken"
}
###

GET {{Web_HostAddress}}/api/reservationStatus/9a5639ba-a59e-42a8-892b-30bb40b6334e
Accept: application/json

###
