@Web_HostAddress = http://localhost:5268

POST {{Web_HostAddress}}/api/createReservationJob
Accept: application/json
Content-Type: application/json

{
  "trainingId": "exampleTrainingId",
  "memberId": "exampleMemberId",
  "userToken": "exampleUserToken"
}
###

GET {{Web_HostAddress}}/api/reservationStatus/550f6115-4a56-4adf-a221-774dadcec38c
Accept: application/json

###
